[server]
# Increase timeout settings
headless = true
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

# Increase the timeout values
connectionTimeout = 300
runOnSave = false

# Memory management options
[runner]
# Memory management
magicEnabled = true
fastReruns = true

[browser]
# Auto-close when app is not running
gatherUsageStats = false

[theme]
primaryColor = "#0078d4"
backgroundColor = "#f3f2f1"
secondaryBackgroundColor = "#ffffff"
textColor = "#323130"
